Documentation:
  Enabled: false
Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be an Integer or
  # a Float.
  Max: 15

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 200

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 200

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Max: 6

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'app/models/match_conversation_instance.rb'
    - 'spec/factories/match_conversation_instances.rb'
    - 'spec/models/match_conversation_instance_spec.rb'
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 24

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 12

SingleSpaceBeforeFirstArg:
 Exclude:
   - app/views/api/**/**/*

Style/Lambda:
  Exclude:
    - 'app/models/target.rb'
